import type { Monaco } from '@monaco-editor/react'

export type MonacoThemeData = Parameters<Monaco['editor']['defineTheme']>[1]

export const jsonCraftDark: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'string.value.json', foreground: '86efac' },
    { token: 'string.key.json', foreground: '7dd3fc' },
    { token: 'number.json', foreground: 'fcd34d' },
    { token: 'keyword.json', foreground: 'c4b5fd' },
    { token: 'delimiter.array.json', foreground: 'f0abfc' },
    { token: 'delimiter.object.json', foreground: 'f0abfc' },
    { token: 'delimiter.json', foreground: '71717a' },
    { token: 'string.invalid.json', foreground: 'f87171' },
  ],
  colors: {
    'editor.background': '#09090b',
    'editor.foreground': '#e4e4e7',
    'editorLineNumber.foreground': '#3f3f46',
    'editorLineNumber.activeForeground': '#71717a',
    'editor.lineHighlightBackground': '#ffffff06',
    'editor.selectionBackground': '#8b5cf630',
    'editor.selectionHighlightBackground': '#8b5cf618',
    'editorCursor.foreground': '#8b5cf6',
    'editor.inactiveSelectionBackground': '#8b5cf615',
    'editorBracketMatch.background': '#8b5cf622',
    'editorBracketMatch.border': '#8b5cf6',
    'scrollbarSlider.background': '#27272a80',
    'scrollbarSlider.hoverBackground': '#3f3f46',
    'scrollbarSlider.activeBackground': '#52525b',
    'editorOverviewRuler.border': '#00000000',
    'editorWidget.background': '#18181b',
    'editorWidget.border': '#27272a',
    'editorSuggestWidget.background': '#18181b',
    'editorSuggestWidget.border': '#27272a',
    'editorSuggestWidget.selectedBackground': '#27272a',
    'input.background': '#27272a',
    'input.border': '#3f3f46',
    'editorError.foreground': '#f87171',
    'editorWarning.foreground': '#fbbf24',
    'editorGutter.background': '#09090b',
    'editor.wordHighlightBackground': '#8b5cf615',
    'editor.findMatchBackground': '#8b5cf640',
    'editor.findMatchHighlightBackground': '#8b5cf620',
  },
}

export const jsonCraftLight: MonacoThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'string.value.json', foreground: '16a34a' },
    { token: 'string.key.json', foreground: '0369a1' },
    { token: 'number.json', foreground: 'd97706' },
    { token: 'keyword.json', foreground: '7c3aed' },
    { token: 'delimiter.array.json', foreground: '9333ea' },
    { token: 'delimiter.object.json', foreground: '9333ea' },
    { token: 'delimiter.json', foreground: '71717a' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#09090b',
    'editorLineNumber.foreground': '#a1a1aa',
    'editorLineNumber.activeForeground': '#52525b',
    'editor.lineHighlightBackground': '#f9fafb',
    'editor.selectionBackground': '#8b5cf630',
    'editorCursor.foreground': '#7c3aed',
    'editorBracketMatch.background': '#7c3aed15',
    'editorBracketMatch.border': '#7c3aed',
    'scrollbarSlider.background': '#e4e4e780',
    'scrollbarSlider.hoverBackground': '#d4d4d8',
    'editorOverviewRuler.border': '#00000000',
    'editorWidget.background': '#ffffff',
    'editorWidget.border': '#e4e4e7',
    'editorError.foreground': '#dc2626',
    'editorWarning.foreground': '#d97706',
    'editor.findMatchBackground': '#8b5cf640',
    'editor.findMatchHighlightBackground': '#8b5cf620',
  },
}
